### ISSUE TITLE
Raise exception if response is shorter than expected

### ISSUE THREAD

**Issue by meeee** [Barzahlen/grac#12]
When a response is shorter than indicated by the `Content-Length` header, raise an exception.

We don't want to process incomplete data (for non-JSON responses) or try to parse an incomplete JSON document.

Maybe, we can use Typhoeus Response' `success?` method as shown in [their documentation](https://github.com/typhoeus/typhoeus#handling-http-errors).

**Comment by tobischo** [comment]
Well, success would only work for successful responses: https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/response/status.rb#L48
We'd still run into similar issues for JSON responses for errors

**Comment by meeee** [comment]
So, maybe `return_code` is a better option. No idea whether it's part of the public API though.

**Comment by tobischo** [comment]
https://github.com/typhoeus/typhoeus/blob/181834e2483d392d0f7ab0cd17f544cd252c7b2f/lib/typhoeus/response/informations.rb should be

**Comment by tobischo** [comment]
Resolved in #15
